### ISSUE TITLE
Discover: Spelling

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#12]
add an apostrophe: If at at first you **don't** succeed, try again
![Screen Shot 2022-04-29 at 8 58 14 AM](https://user-images.githubusercontent.com/78186896/165949424-549cecd5-739f-400c-94cf-3d2587003fbd.png)

To reproduce: 
1) Go to discover, thinglink
2) Go to main menu, click on "Innovating for Israel"

**Comment by Joshwaaaa** [comment]
@chayaml pls close
