### ISSUE TITLE
Discover: Clicking the correct answer shows that it is incorrect 

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#13]
As I clicked the answer to the left (SpaceIL's mission is to...), it turned red as being incorrect. Could we switch it so clicking on it turns green to indicate it's the correct answer? 

![Screen Shot 2022-04-29 at 9 06 36 AM](https://user-images.githubusercontent.com/78186896/165950811-18619110-cec7-43e0-a037-a6c0e144587e.png)...)

To reproduce:

1) Go to discover, thinglink
2) Go to main menu, click on "Innovating for Israel"
3) Click on the home icon on the top right

Side note: Can the slashes be replaced with commas in the correct answer?

**Comment by Joshwaaaa** [comment]
@chayaml fixed please close thanks
(unfortunately it needs to be slashes as when you enter a comma it takes that as a new answer option. i moved the slashes closer together so it didnt look as bad).
