### ISSUE TITLE
Discover: Can't see the youtube video/ link not clickable

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#14]
"Watch this video", clicking on the play icon does not produce a YouTube video popup/the link that appears is not clickable 

![Screen Shot 2022-04-29 at 9 25 24 AM](https://user-images.githubusercontent.com/78186896/165954880-a60bb7ac-6915-4adb-b0db-e02f6465663d.png)

To reproduce:

1) Go to discover, thinglink
2) Go to main menu, click on "Applications for the world"
3) Click on "Helios"

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
