### ISSUE TITLE
Watch: Open ended question - spelling  and wording

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#17]
In the open ended question from the first video:
How **do** (does?) Israel's choice of songs for this European competition reflect nostalgia for Israel's past or **it's** (should be its) modern sound?

The wording of this question could be edited to improve clarity :)

Possible suggestions... 
- In what way does Israel's choice of songs for this European competition reflect nostalgia for its past or its modern sound? 
-  Is Israel's choice of songs for this European competition a nod to its past or a reflection of its modern sound?
- Can Israel's selection of songs for this European contest be seen as a nostalgia for its past or as its modern sound?

![Screen Shot 2022-04-29 at 3 47 56 PM](https://user-images.githubusercontent.com/78186896/166061947-3ad06264-b8a1-4c84-8113-93160fa18612.png)

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
