### ISSUE TITLE
Watch: Multiple choice questions - any answer should be marked as correct

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#18]
![Screen Shot 2022-04-29 at 4 13 12 PM](https://user-images.githubusercontent.com/78186896/166063148-2cb36bef-0436-476e-87a1-8d76983be9c4.png)

**Comment by Joshwaaaa** [comment]
@chayaml hi do u know why i cant tag carina on this one?

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
