### ISSUE TITLE
Watch: Wording/ typos

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#19]
In the last answer:

 No, because Hebrew is that (change to **the**) national language of Israel, so only songs with Hebrew lyrics should be included.

or better yet: Since Hebrew is the national language of Israel, only songs with Hebrew lyrics should be included. 

![Screen Shot 2022-04-29 at 4 18 30 PM](https://user-images.githubusercontent.com/78186896/166064308-5b7b862e-bb3e-4211-9840-8cb4ae74e393.png)

(also any answers should be accepted as correct)

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
