### ISSUE TITLE
Quiz: Puzzle is positioned too low

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#2]
The puzzle appears too low on the screen when I am using full screen 
![Screen Shot 2022-04-17 at 7 08 05 PM](https://user-images.githubusercontent.com/78186896/163723208-b514e27f-1dcd-4ad2-8918-a87939f41368.png)

**Comment by crockji** [comment]
@chayaml I'm not sure how to fix this one.  Will have a look in puzzle. But I think we have to live with it.

**Comment by Joshwaaaa** [comment]
@chayaml when i test this out on 100% view the crossword appears correctly. @crockji can u test on your machine and see how it looks. 
![crossword](https://user-images.githubusercontent.com/87075049/169054206-79ec4d4c-e606-4071-90fe-36022310c59a.jpg)
