### ISSUE TITLE
Watch: Wording/ spelling

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#20]
Eddie Butler's name is misspelled (only one 't') :)

Text change suggestion:

Do you recognize Eddie Butler?
In 1999, he represented Israel at the Eurovision Contest with the group Eden.
Eddie was born in Dimona, Israel to a family of Black Hebrew Israelites from Chicago.

![Screen Shot 2022-04-29 at 4 31 34 PM](https://user-images.githubusercontent.com/78186896/166065806-bafb7eb9-e688-46a6-842a-0982dca62519.png)

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
