### ISSUE TITLE
Watch: typos and text edit

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#22]
a) The question mark in the first sentence should be replaced with a period

b) For clarity, I edited the text with two versions, one closer to the original :)

- Netta is the latest Israeli winner of Eurovision.
What changes have you noticed in the musical styles of Israel's song choices over the years, especially in the late 2010s? Are those choices reflective of how Israel wants to be perceived by the world?

-   Israel's Eurovision song selections have evolved over the last few decades, culminating with Netta as the latest winner of Eurovision. How does this shift reflect how Israelis hope to be perceived by the world?

![Screen Shot 2022-05-02 at 3 09 01 PM](https://user-images.githubusercontent.com/78186896/166310299-f9f86f30-d953-412a-8554-8e1226ad74bf.png)

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
