### ISSUE TITLE
Watch: 2nd video

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#23]
Replace question mark with period

(btw I'm not sure I understand what to look for - the only reference to Israeli contestants was the word Hebrew")
![Screen Shot 2022-05-04 at 8 22 18 PM](https://user-images.githubusercontent.com/78186896/166847967-b2b7adc4-d82e-489d-8601-46617ef6910a.png)

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
