### ISSUE TITLE
Watch: 2nd video - spelling

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#24]
the word participate is misspelled.

Edit suggestion: In light of this description, why would Israel want to take part in Eurovision? 

![Screen Shot 2022-05-04 at 8 23 15 PM](https://user-images.githubusercontent.com/78186896/166848343-2a3d5d10-fa12-414c-862c-5520b9e0e3f1.png)

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
