### ISSUE TITLE
Watch: 2nd video - spelling

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#25]
The word "languages" and "sung" are misspelled. 

![Screen Shot 2022-05-04 at 8 26 32 PM](https://user-images.githubusercontent.com/78186896/166848872-78e098c1-3641-4468-8053-93d6e0462d68.png)

change to: Can you name any other languages in which Israel's contestants may have sung lyrics?

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
