### ISSUE TITLE
Discover: Thinglink - video unavailable 

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#27]
![Screen Shot 2022-05-04 at 9 48 45 PM](https://user-images.githubusercontent.com/78186896/166853128-80bd5e51-4b25-4fc1-b34c-2a5655a2ee01.png)
Video unavailable when clicking on the web icon - I know this can happen again as it's up tp the owner...

To reproduce:
1) thinglink, main menu
2) click on representing Israel's story
3) click on top right arrow
4) click on top right arrow
5) click on web icon by "netta"

**Comment by Joshwaaaa** [comment]
@chayaml fixed thx pls close
