### ISSUE TITLE
Discover: thinglink - grammer

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#28]
Replace **"artist"** with **"artists"**

![Screen Shot 2022-05-04 at 9 58 50 PM](https://user-images.githubusercontent.com/78186896/166853740-eafb6dc7-4e95-4288-a9d1-acc82bf216ec.png)

or ...
Which of these artists representing Israel's diversity did not win the Eurovision contest?

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
