### ISSUE TITLE
Discover: Thinglink - Spelling

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#29]
Nadav Guedj's first name is misspelled (bottom left)
Kobi Marimi's first name is misspelled (bottom right)
![Screen Shot 2022-05-04 at 10 21 23 PM](https://user-images.githubusercontent.com/78186896/166855291-bfa0bf04-9c9d-4db0-8ab9-beecaec69232.png)

To reproduce:
1) Discover, thinglink, main menu
2) Click on representing Israel's story
3) click on top right arrow 4x

**Comment by chayaml** [comment]
![Screen Shot 2022-05-04 at 10 31 03 PM](https://user-images.githubusercontent.com/78186896/166855809-6bb52c5f-f51f-43b6-b254-0079ecbb7c7a.png)
here too - kobi marimi

**Comment by Joshwaaaa** [comment]
@chayaml pls close
