### ISSUE TITLE
Watch: 1st video - 3rd question - grammar

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#32]
![Screen Shot 2022-05-05 at 3 56 30 PM](https://user-images.githubusercontent.com/78186896/167015525-ec85a38c-1bc0-4748-b7e8-c9ffdcbe2664.png)

1) What are reasons for what makes Israeli music special in the world - change to - What are **the** reasons for what makes Israeli music special in the world
or perhaps:
Why is Israeli Music special in the world?  // What is it about Israeli music that makes it so special?

2) Change the first answer to: Its roots are in classical European music.  // Traditionally, it is based on classical European music.

**Comment by chayaml** [comment]
By the way, the answer to this question appears after this question is posed in the video

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
