### ISSUE TITLE
Watch: 2nd video - 3rd question - grammar

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#34]
Question isn't phrased right... change to:

Which of these Israeli songs is your favorite? 

![Screen Shot 2022-05-05 at 4 22 07 PM](https://user-images.githubusercontent.com/78186896/167019356-11a70d4b-c9e6-4e4f-a432-e35357bb987c.png)

**Comment by Joshwaaaa** [comment]
@chayaml pls close
