### ISSUE TITLE
Discover: Thinglink -  grammar 

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#35]
![Screen Shot 2022-05-05 at 4 33 33 PM](https://user-images.githubusercontent.com/78186896/167021003-e28362af-15b5-40fe-a58e-ccc8c4dfb8a8.png)

Change to: What is **a** Sabra?

To reproduce:
1) Discover, thinglink, main menu
2) click on "myth makers"
3) click on " the sabra"
4) click on home icon on top right

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
