### ISSUE TITLE
Discover - Thinglink - spelling

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#36]
Move Apostrophe in the word Sha'ar in both the title and question
![Screen Shot 2022-05-05 at 4 44 39 PM](https://user-images.githubusercontent.com/78186896/167022581-2ca52d21-af91-472e-ba49-3b660598c088.png)

![Screen Shot 2022-05-05 at 4 41 30 PM](https://user-images.githubusercontent.com/78186896/167022162-fbdd9cdf-e7df-4aad-90f3-032dc52f974b.png)

To reproduce:

1) Discover, thinglink, main menu
2) click on "myth makers"
3) click on "collective memory loss"
4) For the question click on home icon on top right

**Comment by Joshwaaaa** [comment]
2nd issue fixed. 1st issue sent to rochi

**Comment by Joshwaaaa** [comment]
@chayaml pls close
