### ISSUE TITLE
Discover: Thinglink - 

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#37]
1) By answer 3 change to **an** Israeli singer
2) All the answers are marked as incorrect

![Screen Shot 2022-05-05 at 4 55 40 PM](https://user-images.githubusercontent.com/78186896/167024232-93560cdf-6a2b-4fc6-bd65-e9cd2d781021.png)
![Screen Shot 2022-05-05 at 4 56 11 PM](https://user-images.githubusercontent.com/78186896/167024342-25eb14a8-abef-4b49-934f-902655d3d9ad.png)

To reproduce:
1) discover, thinglink, main menu
2) click on "mythmakers"
3) click on "rebirth of the nation"
4) click on home button on top right

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
