### ISSUE TITLE
Discover: Thinglink - grammar

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#38]
Change to: "Where does the song "Had Gadya" originate **from?**

![Screen Shot 2022-05-05 at 5 04 42 PM](https://user-images.githubusercontent.com/78186896/167025833-9be4e862-b373-4a6f-b712-2daaae609aa0.png)

To reproduce:
1) discover, thinglink, main menu
2) click on "myth breakers"
3) Click on "has zionism strengthened jewish identity?"
4) click on home icon at top right

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
