### ISSUE TITLE
Watch: 1st video - 1st question - spelling

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#40]
Change Yeminite to Yemenite 
![Screen Shot 2022-05-05 at 5 28 52 PM](https://user-images.githubusercontent.com/78186896/167029110-66bca6b8-39d3-44c7-bcf9-5acc87b2c51a.png)

**Comment by chayaml** [comment]
also appears by the third and fourth questions

**Comment by Joshwaaaa** [comment]
@chayaml pls close
