### ISSUE TITLE
Discover: Thinglink

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#44]
1) None of the answers are marked as correct
2) Can the commas be removed?
![Screen Shot 2022-05-05 at 6 58 07 PM](https://user-images.githubusercontent.com/78186896/167041256-de6b46eb-25b0-472c-a3f0-ed19f8cc9f9e.png)
3) change to "try again to move **on**"?
![Screen Shot 2022-05-05 at 7 09 51 PM](https://user-images.githubusercontent.com/78186896/167041592-21591674-e349-454a-b337-c77d1ee69c9f.png)

To reproduce:
1) discover, thinglink, main menu.
2) click on "yemenite jews"
3) click on top right arrow

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
