### ISSUE TITLE
Discover: Thinklink

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#47]
1) None of the answers are marked as correct
![Screen Shot 2022-05-05 at 8 23 56 PM](https://user-images.githubusercontent.com/78186896/167047495-f741f1b6-4673-4dc5-9a39-6e3a46412ee4.png)

To reproduce:

1) discover,  thinglink, main menu
2) click on "new hip hop"
3) click on top right arrow

**Comment by Joshwaaaa** [comment]
@chayaml fixed pls close
