### ISSUE TITLE
Discover: All plays lead to same video?

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#49]
The videos for all Circles (Abraham & the Covenant, the Enlightenment, Modern Zionism) are the same? Is the video supposed to be broken up into topics?

To reproduce:

1. Discover
2. Thinglink - "The true origin of modern Zionism"  slide

![Screen Shot 2022-10-26 at 2 12 54 PM](https://user-images.githubusercontent.com/78186896/198104345-7428f683-e521-451a-b8ee-bde72a35ceb8.png)

**Comment by yechielhoffman** [comment]
I have removed the youtube links, which didn't start at the clips as was intentioened.
I resolved this by creating new video clips using jigzi, and inserted links to the jigs
