### ISSUE TITLE
Discover: Spelling and grammar

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#5]
![Screen Shot 2022-04-17 at 9 12 18 PM](https://user-images.githubusercontent.com/78186896/163727158-10515937-cfc6-45df-bf65-cef5fd6ab802.png)

1) "Israeli's" should be - Israelis 
2) suggestion to edit text:

- Which issues do Israelis face in regard to healthcare?
- What are the problems that Israel faces in regard to healthcare?
-  What are the challenges Israel faces when it comes to healthcare?

To reproduce:
1) Go to Discover, thinglink, main menu
2) Click "mapping the problem"
3) Click on the arrow on the bottom right

**Comment by crockji** [comment]
@chayaml Easy fix.  Thanks for the great suggestions!

**Comment by Joshwaaaa** [comment]
@chayaml how do i mark items as done/fixed? thx

**Comment by chayaml** [comment]
@Joshwaaaa You can click "close issue" or "close with comment" on the bottom right

**Comment by crockji** [comment]
Thanks.  Was wondering the same thing.  I haven't had a chance to go in and
fix all the edits yet.  I will mark them done once I fix them.
*Carina Rock *
*West Coast Director*
***@***.***
jigzi.org
israelbytes.org

**Comment by Joshwaaaa** [comment]
thanks @chayaml 
Sorry i cant see this on my view - am on a desktop/chrome - pls direct me to where close issue/close with comment is...
![image](https://user-images.githubusercontent.com/87075049/166899376-d1bed48b-2574-4ebb-b74b-3fe2165e7bd9.png)

**Comment by chayaml** [comment]
@Joshwaaaa scroll all the way down and you should be able to see the buttons on the bottom right of your screen (after all the comments)
![Screen Shot 2022-05-05 at 4 25 27 PM](https://user-images.githubusercontent.com/78186896/167019865-93309fc3-ad35-42ff-871d-b9f25e4ce637.png)

**Comment by chayaml** [comment]
lmk if you can't find it!

**Comment by Joshwaaaa** [comment]
done - pls close
