### ISSUE TITLE
Discover: thinglink 

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#51]
1) Is it possible to reposition the image so his face isn't cut off?

2) Text correction:

Born in Budapest, **he** moved to Vienna with his family in 1878, where he became a writer, playwright, and journalist. Named “Tivadar” in Hungarian, he is called “Dori,” a shortened version of his German name, “Wolf Theodor.”

![Screen Shot 2022-10-27 at 2 55 05 PM](https://user-images.githubusercontent.com/78186896/198374994-2cee0096-d635-4b0a-9460-e3eccc75ccda.png)

![Screen Shot 2022-10-26 at 2 47 09 PM](https://user-images.githubusercontent.com/78186896/198110888-7cdead0e-dadc-42d4-9802-adc70996831c.png)

To reproduce:

1. Discover
2. Thinglink - main menu
3. Click on "visionaries of a nation"
4. Click on theodor herzl
5. Click on "beginnings"

**Comment by yechielhoffman** [comment]
resolved typo
Thinglink will not allow for image realignment
