### ISSUE TITLE
Discover: Thinglink  - text and grammer

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#53]
Grammar and text edits:

**Text that contains errors:**
In February 1896, Herzl published “The Jewish State,” calling upon Jews to obtain their own territory, to create institutions and forums to oversee Jewish **immigration **to** and settlement **in this territory****, and to ultimately create their own state.
In addition to creating the World Zionist Organization, Herzl **will help** found the Jewish Colonial Trust in 1899 and the Jewish National Fund in 1901.

**Text edit:**
In February 1896, Herzl published "The Jewish State," calling upon Jews to obtain their own territory, establish institutions and forums to oversee Jewish **immigration and settlement**, and, ultimately, establish their own state. In addition to creating the World Zionist Organization, Herzl **helped found** the Jewish Colonial Trust in 1899 and the Jewish National Fund in 1901.

![Screen Shot 2022-10-27 at 2 22 12 PM](https://user-images.githubusercontent.com/78186896/198382424-0b476577-519e-428e-a560-48063a4d020c.png)

To reproduce:

1. Discover
2. Thinglink - main menu
3. Click on "visionaries of a nation"
4. Click on Theodor Herzl
5. Click on "key accomplishments"

**Comment by yechielhoffman** [comment]
Revised copy
