### ISSUE TITLE
Discover: Thinglink - text punctuation

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#54]
Punctuation fix:

Chaim Weizmann was born in Motol, Russia on November 27, **1874.  Weizmann** received his education in biochemistry in Switzerland and Germany.
Already living in Geneva, he became active in the Zionist movement. In 1905 he moved to England, and was elected to the General Zionist Council.

Also change "already living in Geneva" to "while living in geneva"? unclear

![Screen Shot 2022-10-27 at 4 08 32 PM](https://user-images.githubusercontent.com/78186896/198388936-a0ebbed6-b886-44c1-8355-fd4f1e9e628c.png)

To reproduce:
1. Discover
2. Thinglink - main menu
3. Click on "visionaries of a nation"
4. Click on "who made zionist vision a reality"
5. Click on Chaim Weizmann
6. Click on "beginnings"

**Comment by yechielhoffman** [comment]
Revised copy
