### ISSUE TITLE
Discover - Thinglink: Broken link

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#55]
broken link to henrietta szold youtube video

![Screen Shot 2022-10-27 at 4 34 21 PM](https://user-images.githubusercontent.com/78186896/198398682-638a47d9-5b2c-406b-9950-5f4b9b1df4b5.png)

To reproduce:

1. Discover
2. Thinglink - main menu
3. Click on "visionaries of a nation"
4.  on "who made zionist vision a reality"
5. Click on Henrietta Szold
6. Click on play button by the image

**Comment by yechielhoffman** [comment]
removed button
