### ISSUE TITLE
Discover- thinglink: typo and editing suggestion

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#57]
![Screen Shot 2022-11-01 at 1 40 25 PM](https://user-images.githubusercontent.com/78186896/199301474-2f528689-3ba5-43a9-a20d-c79809ef12ea.png)

As a teenager living in Plonsk, David founded the "Ezra" association, dedicated to Zionist education and Hebrew teaching.

David immigrated to Palestine in 1906, where he worked in agriculture on various farming settlements. He soon joined the leadership of the Poalei Zion party ("Workers of Zion").

In 1910, David was appointed to the editorial board of He’ahdut ("Unity"), the party's newspaper, and for the first time penned articles under his new name, Ben-Gurion. Ben-Gurion established US branches of Hehalutz ("The Pioneer"), a Zionist movement training young people for immigration to Israel.

Following the Balfour Declaration in 1917, Ben-Gurion recruited Jews in the United States to volunteer for the Jewish Legion in the British Army.

**Comment by yechielhoffman** [comment]
Revised copy
