### ISSUE TITLE
Discover: Thinglink - content mix up

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#58]
There seems to be a mix up - the button by "What are the leader's legacies" opens a window about Golda's life and clicking on Golda's picture opens the window about the leader's legacies. They need to be switched.

![Screen Shot 2022-11-01 at 2 30 52 PM](https://user-images.githubusercontent.com/78186896/199311448-e3cdbb80-cbe0-4b83-b74d-a1e57a1f3578.png)

**Comment by yechielhoffman** [comment]
revised thinglink navigation and caption
