### ISSUE TITLE
Discover: Thinglink - spelling and text edits

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#59]
1) Change to "addresses"

![Screen Shot 2022-11-01 at 2 50 06 PM](https://user-images.githubusercontent.com/78186896/199314814-954c3d51-f2b6-4533-ab1b-1d7e76a4c77c.png)

2) _Text edit suggestion_:

In 1960, Argentina complained to the Security Council of the United Nations that Israel had violated its sovereignty by capturing Adolph Eichmann on its territory and bringing him to Israel for trial. After Golda addresses the UN with a powerful speech about the Holocaust, the Council decides that an expression of regret from Israel is sufficient and endorses the idea of bringing the wanted Nazi to trial.

**Comment by yechielhoffman** [comment]
revised title and copy
