### ISSUE TITLE
Discover: Text edits

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#6]
![Screen Shot 2022-04-17 at 9 40 05 PM](https://user-images.githubusercontent.com/78186896/163728154-0bc9dbf2-ae7f-4605-b6af-6df4a89d0b57.png)
1) Meeting the health of every person - change to - meeting the health **needs** of every person
2) don't rely on buying expensive medical devices from other countries - change to - Not relying on expensive medical devices imported from around the world.

To reporduce:
1) go to discover, thinglink, main menu
2) Click on "mapping the problem"

**Comment by crockji** [comment]
@chayaml love these suggestions.  This will have to go through @Rochi

**Comment by Joshwaaaa** [comment]
@chayaml pls close

**Comment by Joshwaaaa** [comment]
@chayaml pls close
