### ISSUE TITLE
Discover: Thinglink - typo and text edit

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#60]
1) change to secret

![Screen Shot 2022-11-06 at 8 47 51 PM](https://user-images.githubusercontent.com/78186896/200210424-577a9c77-4f1d-411a-8293-bc3c111abad8.png)

2) text edit suggestion:

Golda Meir secretly met with King Abdullah in Jordan in May 1948, while disguised as a Muslim woman. She hoped to convince him to keep Jordan out of the war with Israel. The King showed her respect, but did not respond to her pleas.

**Comment by yechielhoffman** [comment]
Revised title and copy
