### ISSUE TITLE
Discover: Thinglink - text edit

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#61]
Text edit suggestion:

Yitzhak Rabin was born in Jerusalem on March 1, 1922, and grew up in Tel Aviv. As a child, he was raised according to the values of the Labor movement by his parents, Nehemia Rabin and Rosa Cohen, who were active in the political party, Ahdut Ha'avoda. When he was 15, his mother died of an illness.

![Screen Shot 2022-11-06 at 9 29 34 PM](https://user-images.githubusercontent.com/78186896/200214891-5ae6c003-a630-4fa0-a993-644c09e00670.png)

**Comment by yechielhoffman** [comment]
revised copy
