### ISSUE TITLE
Discover: thinglink - text edit

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#62]
Text edit suggestion:

In 1941, he was one of the first to join the Haganah’s elite strike force, the Palmach. In 1945, he led a raid on a British camp in Athlit north of Herzlia to free illegal Jewish immigrants. At the end of 1946, he became a battalion commander, and by 1947, he was Palmach's chief operations officer.

![Screen Shot 2022-11-06 at 9 49 23 PM](https://user-images.githubusercontent.com/78186896/200216298-20f1aae2-3719-4389-b3de-a8ff98cc591d.png)

**Comment by yechielhoffman** [comment]
revised copy
