### ISSUE TITLE
Discover: Thinglink - text edit suggestion

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#65]
Outcomes of the Agreement
The agreement strengthened Israel's and Egypt's commitment to abiding by UN Resolution 338, the ceasefire agreement that ended the Yom Kippur War.
In addition, the agreement  strengthened diplomatic relations between Egypt, Israel, and the United States.

In turn, this led to the 1978 Camp David Accords and the subsequent 1979 peace treaty between Egypt and Israel, which laid the framework for a peaceful settlement of the conflict between Israel and its neighbours.

As part of the return of the Sinai to Egypt, Israel evacuated and razed Yamit, the last Israeli settlement in the Sinai, on April 23, 1982, amid strong domestic opposition. The three-year process of Israel's complete withdrawal from the strategically vital and mineral-rich Peninsula ends two days later. Upon completion of this act, Israel has fulfilled its 1979 treaty promise to Egypt.

In return, Egypt acknowledges Israel’s right to exist, and promises to live peacefully as neighbours.

The peace treaty with Egypt is the first between Israel and any of its Arab neighbours, and it remains in effect today.

![Screen Shot 2022-11-07 at 11 20 46 AM](https://user-images.githubusercontent.com/78186896/200370659-2b796ce0-389d-4b1c-bb43-7d667276b7dc.png)

To reproduce:
1) thinglink - main menu - click pulse to start
2) act with others
3) What did Menachem... (middle circle)
4) Outcomes of the decision

**Comment by yechielhoffman** [comment]
revised copy
