### ISSUE TITLE
Discover: thinglink - typo/ grammar

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#66]
1) remove "of"

![Screen Shot 2022-11-07 at 12 07 09 PM](https://user-images.githubusercontent.com/78186896/200371704-220575f5-b7a2-43d0-99f5-b408677c2eb0.png)

2) change to " Eastern", remove comma, change T to lowercase.

![Screen Shot 2022-11-07 at 12 10 38 PM](https://user-images.githubusercontent.com/78186896/200372806-921a7668-ab5c-476f-b71b-af4e4ee03116.png)

**Comment by yechielhoffman** [comment]
revised typos
