### ISSUE TITLE
Discover: thinglink - grammar and spelling

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#69]
Suggested edit:

Shamir's decision not to intervene in the Gulf War, and to let the US deal with Iraq, strengthened ties with the United States, who appreciated his leadership, and further increased aid and military support. Shamir's decision became a model for other leaders to practice saying "no" to their opponents and allies.

As a member of the "Stern Gang", Shamir's decision solidified the idea that there must be a Jewish state that could act freely and independently of all nations, even when it meant not acting at all.

![Screen Shot 2022-11-07 at 2 13 45 PM](https://user-images.githubusercontent.com/78186896/200398064-aec8192a-fb89-4837-85b7-ea4ca89fbba3.png)

**Comment by yechielhoffman** [comment]
revised copy
