### ISSUE TITLE
Discover: Spelling

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#7]
![Screen Shot 2022-04-17 at 9 47 47 PM](https://user-images.githubusercontent.com/78186896/163728571-dded0e3a-1478-4aa8-9a7c-f7157d08382f.png)

 Change Israeli's to Israelis

To reproduce:
1) Go to discover, thinglink, main menu
2) Click on "innovating for Israel"
3) Click on "testing innovation"
4) Click on house icon on top right of screen

**Comment by crockji** [comment]
Easy fix.   Thanks!!!

**Comment by Joshwaaaa** [comment]
hi @chayaml i think maybe because i have basic account i can't close item - doesnt look like i have that option
I can comment here for you to close them when done? 
this one is done. thank you!
