### ISSUE TITLE
Discover: thinglink - text edit

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#70]
Text edit suggestion

Sharon's Legacy

Ariel Sharon entered a coma in 2008, and died eight years later. In spite of Sharon's disengagement plan, the Israeli-Palestinian conflict remains stalemated. Whether as a result of Sharon's policies or not, the number of Israeli civilians killed by Palestinians decreased as his separation policies took effect, falling from 264 in 2002 to seven in 2007. In most cases, Israeli casualties have been caused by rocket fire from Gaza, not suicide bombings. Despite this, no tangible progress has been made in the peace process during this time period.

In 2008, Sharon's handpicked successor, Ehud Olmert, was reportedly close to an agreement with Palestinian President Mahmoud Abbas, but the talks collapsed as war broke out between Israel and Hamas.

The situation on the ground has been frozen ever since. The separation barrier that Sharon proposed remains standing, complicating the lives of Palestinians and sometimes separating them from their land. Sharon, someone who was always aware of how “facts on the ground” determined final outcomes, never said the barrier route would be permanent, but it doesn't appear to be going away any time soon. Many Israelis today believe there is "no partner for peace" on the Palestinian side, as Sharon argued years ago. This belief only intensified as Hamas took power in Gaza in the wake of the withdrawal and fired rockets at Israel.

There are some Israelis who believe that security can be achieved without a formal peace agreement with the Palestinians by separating from them. Likud-Beiteinu and Yesh Atid, the two most popular blocs in the 2013 election, downplayed the conflict and focused instead on Iran and domestic issues instead of supporting parties on the left and far-right that advocated decisive action on the Palestinian issue.

![Screen Shot 2022-11-07 at 2 58 28 PM](https://user-images.githubusercontent.com/78186896/200403035-87408164-1ce8-433c-8b36-f2eb138e11d0.png)

**Comment by yechielhoffman** [comment]
revised copy
