### ISSUE TITLE
End of sentence cut short?

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#72]
![Screen Shot 2022-11-07 at 3 13 08 PM](https://user-images.githubusercontent.com/78186896/200405726-82e389b5-1490-41e1-9b9a-0ccf4e897972.png)

**Comment by chayaml** [comment]
This topic explores how the power of leadership yields to the responsibility of making decisions that no one wants to make. Leaders who leave a legacy are willing to seek pragmatic solutions, even if they need to compromise sometimes

**Comment by yechielhoffman** [comment]
revised copy
