### ISSUE TITLE
Watch: size of player much smaller than previous modules

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#73]
Video/player is quite small and cannot be expanded. In the previous modules, it occupied a larger portion of the screen. Is it possible to make it the same size as the other modules?

Size in diverse leadership:
![Screen Shot 2022-11-08 at 10 57 49 AM](https://user-images.githubusercontent.com/78186896/200614600-4b28869f-0ee9-45a0-b4f3-c9fff96258a4.png)

size in previous modules:
![Screen Shot 2022-11-08 at 10 58 44 AM](https://user-images.githubusercontent.com/78186896/200614784-796c775c-a59e-40df-80ea-f9e501388b46.png)

**Comment by yechielhoffman** [comment]
revised frame size in the embed code
