### ISSUE TITLE
Discover: Thinglink - text edit

### ISSUE THREAD

**Issue by chayaml** [chayaml/Israel-bytes#76]
![Screen Shot 2022-11-08 at 11 22 55 AM](https://user-images.githubusercontent.com/78186896/200638119-370fd9d9-534f-42a1-8d60-b6533c87ba39.png)

text edit suggestion:

Pnina was born in 1981 into the Beta Israel community in Ethiopia. She spent her first years in a refugee camp in Sudan, before coming to Israel through Operation Moses.

During 2013-2015, she represented the secular party, Yesh Atid, in the Israeli parliament, the Knesset. Her social and political commitment earned her recognition in Israel and abroad.

On May 1, 2020, Tamano-Shata was appointed minister of immigration and integration after being reelected to the Knesset.

She is the first Ethiopian Israeli to hold a leading position in Israel's government.

**Comment by yechielhoffman** [comment]
revised copy
